### ISSUE TITLE
Improve display of locations

### ISSUE THREAD

**Issue by drorm** [mapswithme/api-android#13]
It would be nice if there was a way to choose the image/color that is used for the location.  That way, we could chose different colors to indicate different types of objects.

**Comment by kw217** [comment]
I've raised an issue for this against mapsme/omim, see https://github.com/mapsme/omim/issues/238

**Comment by kw217** [comment]
The underlying support is now added to MAPS.ME per the issue above. My plan now is to expose this to Android.

**Comment by drorm** [comment]
This is now a duplicate of mapsme/omim#238
